### PR TITLE
Refund when Jutsu Forgotten && Blocklist UserName now appears in Settings && Blocklisted User's Post don't pop up in chat

### PR DESCRIPTION
**Pull request by MiteyDrill**
- 10% refund

### CODE REVIEW

**Comment by MiteyDrill** [comment]
image
The username wasn't popping up before so you couldn't tell who was blacklisted.

**Comment by MiteyDrill** [comment]
image
Forgetting a Jutsu now gives 10% refund - The overlap is due to the CSS Position: relative - property

**Comment by MiteyDrill** [comment]
srry about the long name

**Comment by MiteyDrill** [comment]
@levimeahan pls review

**Review by levimeahan — APPROVED** [review]

**Pull request merged**
