### PR TITLE
Avy in its own Column

### PR DESCRIPTION
**Pull request by MiteyDrill**
- Added avy column to the Chat page
 - Avy is now bigger
 
 
image

### CODE REVIEW

**Comment by levimeahan** [comment]
Hmm, I think this takes up too much horizontal space. We're already squeezing both chat messages and people with names a little on the long side

**Comment by MiteyDrill** [comment]
Ok, would you like the avy column to be shorten a bit and the User column to take up the extra space so it has more breathing room, or do we leave things as they are atm

**Comment by levimeahan** [comment]
> 
> 
> Ok, would you like the avy column to be shorten a bit and the User column to take up the extra space so it has more breathing room, or do we leave things as they are atm

I'd say leave things as they are atm, although we could try increasing avatar size a bit more. Maybe 50px

**Comment by MiteyDrill** [comment]
Ok sounds good👍

**Pull request closed without merging**
