### PR TITLE
changes

### PR DESCRIPTION
**Pull request by Algharna**
https://github.com/levimeahan/shinobi-chronicles/commit/2b7de052e8037eae02dd78a4ebbfce65c4bb8db3
https://github.com/levimeahan/shinobi-chronicles/commit/4fbc6bcb8110141173f9d888bb4ce500aa6d4175

### CODE REVIEW

**Comment by levimeahan** [comment]
Can you post a screenshot of what the profile looks like with the new icons?

**Comment by Algharna** [comment]
[Here is how it looks](https://prnt.sc/1rlanud)

**Comment by levimeahan** [comment]
Hmm, cast speed and bloodline skill look pretty unfortunate. Wow seeing these here the vibe really looks more Bleach-esque, especially the sandal 🤔 Not sure we want to go with this set of icons

**Comment by Algharna** [comment]
Figured it was worth a shot to see how it looked. I took the file out of the pull if that's right 🤔

**Comment by levimeahan** [comment]
> 
> 
> Figured it was worth a shot to see how it looked. I took the file out of the pull if that's right 🤔

You'll need to revert the changes on your fork, apart from the kunai purchase and exp display changes (see "Files Changed" on this pull request to see what changes would be applied)

**Pull request closed without merging**
